### PR TITLE
Add turboPy tutorial notebook

### PR DESCRIPTION
**Pull request by AOstenfeld**
It's a start.

Addresses #5

### CODE REVIEW

**Comment by arichar6** [comment]
Nice, this is looking really good! I have two recommendations.

First, rather than have a `csv` diagnostic like would be used for the "command line" version of the app, this notebook should use some sort of other custom diagnostic. I'm thinking something that gathers the output in a buffer (could even use the `CSVOutputUtility` for this) but instead of writing to file at the end, it plots the data. That way you can see the code output right there in the notebook. 

Second, I think a tutorial should have more text/equations around the code, to really describe in detail what you are trying to achieve with the code. If you can add more, that would be really helpful for someone who is trying to use this tutorial to learn about turboPy.

**Comment by AOstenfeld** [comment]
I was trying to address the first point, and I'm not sure how to do that outside of editing the code in core.py. Should we add functionality to turboPy that would allow it to plot the outputs directly.

**Comment by padamson** [comment]
I think it's ok to add matplotlib to environment.yml and then use it in your example notebook. No need to add plotting to turbopy itself, just your notebook. Does this make sense?

**Comment by arichar6** [comment]
matplotlib should go in the environment.yml for this repo, not the core turboPy repo

**Comment by AOstenfeld** [comment]
How is this looking?

**Pull request merged**
